version: '3.8'

services:
  moodle:
    build: .
    container_name: moodle-web
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/moodledata
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - moodle-db-data:/var/lib/mysql

volumes:
  moodle-db-data:
