version: '3'

services:
  moodle:
    build: .
    container_name: moodle-web
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html           # Moodle source files
      - ./moodledata:/var/moodledata     # Moodle data directory (persistent files)
    depends_on:
      - db
    environment:
      - MOODLE_DOCKER_WEB_HOST=moodle

  db:
    image: mariadb:10.6
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - moodle-db-data:/var/lib/mysql    # Persistent DB storage

volumes:
  moodle-db-data: {}
